In [2]:
import torch
import torch.nn as nn

In [15]:
a = torch.tensor([[0.1, 0.2, 0.5], [0.7, 0.12, 0.15], [1., 0.12, 0.15]])
a

tensor([[0.1000, 0.2000, 0.5000],
        [0.7000, 0.1200, 0.1500],
        [1.0000, 0.1200, 0.1500]])

In [17]:
# a[:,0][a[:,0] < 0.8] = 0
b = a[:,0]
b[b < 0.5] = 0
b

tensor([0.0000, 0.7000, 1.0000])

In [18]:
a

tensor([[0.0000, 0.2000, 0.5000],
        [0.7000, 0.1200, 0.1500],
        [1.0000, 0.1200, 0.1500]])

In [28]:
c = a.unsqueeze(dim=0)
c

tensor([[[0.0000, 0.2000, 0.5000],
         [0.7000, 0.1200, 0.1500],
         [1.0000, 0.1200, 0.1500]]])

In [33]:
c[0][:,0]

tensor([0.0000, 0.7000, 1.0000])

In [37]:
su = (c[0][:,0] == 1.).sum()
su
row = torch.where(c[0][:,0] == 1.)
row
# row = (ab_point_label[i][1] == 1.)

(tensor([2]),)

In [44]:
c[0][row,1:3]

tensor([[0.1200, 0.1500]])

In [46]:
loss = nn.MSELoss()
input = torch.randn(3, 5, requires_grad=True)
input.shape

torch.Size([3, 5])

In [47]:
target = torch.randn(3, 5)
target

tensor([[-0.7216, -0.0329, -0.4858,  2.3753, -0.3192],
        [ 0.1442, -0.8391, -0.7905,  2.4424, -0.9289],
        [ 0.6851, -0.2978, -1.1662, -0.3938,  0.3350]])

In [48]:
output = loss(input, target)
output

tensor(1.6983, grad_fn=<MseLossBackward>)

In [49]:
label = torch.randn([2,4096, 3])
label.shape

torch.Size([2, 4096, 3])

In [50]:
targets = label[:,:,0]
targets.shape

torch.Size([2, 4096])

In [70]:
a = torch.randn(2,4096,3, device='cuda:0')
a.shape

torch.Size([2, 4096, 3])

In [71]:
row = torch.tensor([2, 3], device='cuda:0')

In [72]:
a[0][row,1:3]

tensor([[-0.7832, -0.7880],
        [-0.3987,  0.1176]], device='cuda:0')

In [73]:
a[0, row, 1:3]

tensor([[-0.7832, -0.7880],
        [-0.3987,  0.1176]], device='cuda:0')

In [68]:
row = torch.tensor([1354, 1738], device='cuda:0')

In [69]:
a[0][row,1:3]

tensor([[ 0.5838,  1.1541],
        [ 0.7144, -0.2882]], device='cuda:0')

In [90]:
ad = []
ad.append(torch.tensor(0.))
# ad.append(torch.tensor(1.))
ad

[tensor(0.)]

In [91]:
torch.stack(ad).mean()

tensor(0.)

In [3]:
a = torch.tensor([], device='cuda:0', dtype=torch.int64)

In [4]:
len(a)

0

In [6]:
len(torch.tensor([], device='cuda:0', dtype=torch.int64),)

0

In [12]:
import torch
import torch.nn as nn

In [10]:
a = (torch.tensor([ 100, 3030]),)

In [11]:
len(a[0])

2

In [23]:
a = torch.sigmoid(torch.randn(2, 4))
b = torch.sigmoid(torch.randn(2, 4))

In [24]:
mse = nn.MSELoss()
mse(a, b)

tensor(0.1027)

In [21]:
c = a-b
(c.square()).mean()

tensor(2.9090)

In [22]:
c.square()

tensor([[7.8894, 5.3267, 3.4270, 1.5393],
        [0.2646, 3.7188, 0.2768, 0.8294]])

In [1]:
for i in range(1,2) :
    print('hi')

hi


In [8]:
import math
import numpy as np

NUM_EPOCH = 100
lr_list = [1] * NUM_EPOCH
e = math.exp(1)
for i,v in enumerate(lr_list) :
    lr_list[i] = 0.05 * (math.cos(i*math.pi/(NUM_EPOCH*2)))* math.exp(1.*i*-e/NUM_EPOCH)
#     lr_list[i] = 0.05 * math.exp(1.*i*-e/NUM_EPOCH)
print(lr_list)
# lr_list = [0.1, 0.1, 0.05, 0.05, 0.05, 0.02, 0.02, 
#            0.01, 0.01, 0.01, 0.005, 0.002,
#            0.001, 0.0005, 0.0005, 0.0005, 0.0001, 0.0001, 0.00005, 0.00005]

[0.05, 0.04865316251735946, 0.04733092121760996, 0.04603324297661734, 0.044760072860790666, 0.04351133533380851, 0.04228693541925528, 0.04108675982038566, 0.039910677998211255, 0.03875854320908087, 0.03763019350290237, 0.036525452683131156, 0.03544413122962764, 0.03438602718546297, 0.03335092700873027, 0.03233860639039575, 0.03134883103920233, 0.03038135743461612, 0.029435933548784463, 0.02851229953845293, 0.027610188407766852, 0.026729326642862435, 0.0258694348191314, 0.02503022818202251, 0.024211417202223286, 0.023412708106044778, 0.022633803381812992, 0.021874402263050555, 0.021134201189213463, 0.020412894244728436, 0.019710173577058048, 0.019025729794502285, 0.018359252344427215, 0.01771042987259352, 0.017078950564240473, 0.01646450246756338, 0.015866773800205982, 0.015285453239372483, 0.014720230196147639, 0.014170795074597514, 0.013636839516207507, 0.013118056630199177, 0.012614141210252096, 0.012124789938142182, 0.01164970157479352, 0.011188577139226377, 0.01074112007587025, 0.0

In [12]:
# for i in range(100) :
#     lr = 0.1 * (0.1 ** (i / 30))
#     print(lr)