In [64]:
import torch
import numpy as np
import torch.nn as nn

In [8]:
a = torch.ones((5,5))
a

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [9]:
a.type()

'torch.FloatTensor'

In [10]:
a.is_shared()

False

In [11]:
a = a.share_memory_()

In [12]:
a.is_shared()

True

In [15]:
t = torch.ones(5)
print(f"t: {t}")

t: tensor([1., 1., 1., 1., 1.])


In [16]:
n = t.numpy()
print(f"n: {n}")

n: [1. 1. 1. 1. 1.]


In [17]:
t.add_(1)

tensor([2., 2., 2., 2., 2.])

In [18]:
print(f"n: {n}")

n: [2. 2. 2. 2. 2.]


In [20]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [24]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [25]:
x_np.add_(1)

tensor([[2, 3],
        [4, 5]])

In [26]:
np_array

array([[2, 3],
       [4, 5]])

In [27]:
data

[[1, 2], [3, 4]]

In [28]:
x_data

tensor([[1, 2],
        [3, 4]])

In [29]:
tensor = torch.rand(3,4)

In [30]:
tensor.shape

torch.Size([3, 4])

In [31]:
tensor.dtype

torch.float32

In [32]:
tensor.device

device(type='cpu')

In [35]:
tensor = torch.rand(4, 4)
tensor

tensor([[0.5239, 0.1424, 0.7090, 0.4583],
        [0.4863, 0.2209, 0.0108, 0.9114],
        [0.0289, 0.5397, 0.6122, 0.5051],
        [0.9232, 0.9337, 0.3621, 0.9654]])

In [38]:
tensor[..., -1]

tensor([0.4583, 0.9114, 0.5051, 0.9654])

In [40]:
tensor[:,1] = 0

In [41]:
tensor

tensor([[0.5239, 0.0000, 0.7090, 0.4583],
        [0.4863, 0.0000, 0.0108, 0.9114],
        [0.0289, 0.0000, 0.6122, 0.5051],
        [0.9232, 0.0000, 0.3621, 0.9654]])

In [45]:
torch.cat([tensor, tensor],dim=0).shape

torch.Size([8, 4])

In [52]:
torch.stack([tensor, tensor], dim=0)

torch.Size([2, 4, 4])

In [53]:
a = torch.ones((2,3))
b = torch.ones((3,4))

In [54]:
a @ b

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [55]:
c = a.matmul(b)

In [203]:
input = torch.tensor([-0.1, 0.1, 0.2, 0.8, 0.9])
label = torch.tensor([1.,1.,1.,0.,0.])

In [204]:
w1 = torch.randn((1,), requires_grad=True)
w2 = torch.randn((1,), requires_grad=True)
print(w1)
print(w2)

tensor([0.2309], requires_grad=True)
tensor([0.6773], requires_grad=True)


In [205]:
relu = torch.nn.ReLU()
elu = torch.nn.ELU(alpha=1.0, inplace=False)

In [206]:
out = torch.sigmoid(relu(input * w1) * w2)
out

tensor([0.5000, 0.5039, 0.5078, 0.5312, 0.5351], grad_fn=<SigmoidBackward>)

In [207]:
loss = (out - label) ** 2
loss

tensor([0.2500, 0.2461, 0.2422, 0.2822, 0.2864], grad_fn=<PowBackward0>)

In [208]:
loss.sum().backward()

In [209]:
w1 = torch.randn((1,), requires_grad=True) - 1
w1

tensor([0.1685], grad_fn=<SubBackward0>)

In [210]:
# w1 = torch.randn((1,), requires_grad=True) 
# w2 = torch.randn((1,), requires_grad=True) 
w1 = torch.tensor([0.0601], requires_grad=True)
w2 = torch.tensor([0.0520], requires_grad=True)
lr = 0.01
for i in range(100000) :
#     out = torch.sigmoid(relu(input * w1) * w2)
    out = torch.sigmoid(elu(input * w1) * w2)

    loss = (out - label) ** 2
    loss.sum().backward()

    if i % 1000 == 0:
        print(elu(input * w1))
#         print(w1)
    with torch.no_grad():
        w1 -= lr * w1.grad
        w2 -= lr * w2.grad
        w1.grad.zero_()
        w2.grad.zero_()

tensor([-0.0060,  0.0060,  0.0120,  0.0481,  0.0541], grad_fn=<EluBackward0>)
tensor([-0.0170,  0.0171,  0.0342,  0.1369,  0.1540], grad_fn=<EluBackward0>)
tensor([-0.1252,  0.1338,  0.2675,  1.0701,  1.2039], grad_fn=<EluBackward0>)
tensor([-0.1319,  0.1415,  0.2830,  1.1318,  1.2733], grad_fn=<EluBackward0>)
tensor([-0.1312,  0.1407,  0.2814,  1.1254,  1.2661], grad_fn=<EluBackward0>)
tensor([-0.1304,  0.1397,  0.2794,  1.1174,  1.2571], grad_fn=<EluBackward0>)
tensor([-0.1295,  0.1387,  0.2774,  1.1095,  1.2482], grad_fn=<EluBackward0>)
tensor([-0.1287,  0.1377,  0.2754,  1.1018,  1.2395], grad_fn=<EluBackward0>)
tensor([-0.1278,  0.1368,  0.2735,  1.0941,  1.2308], grad_fn=<EluBackward0>)
tensor([-0.1270,  0.1358,  0.2716,  1.0865,  1.2223], grad_fn=<EluBackward0>)
tensor([-0.1262,  0.1349,  0.2698,  1.0791,  1.2139], grad_fn=<EluBackward0>)
tensor([-0.1254,  0.1340,  0.2679,  1.0717,  1.2057], grad_fn=<EluBackward0>)
tensor([-0.1246,  0.1331,  0.2661,  1.0645,  1.1976], grad_fn=<E

In [212]:
out

tensor([0.5489, 0.4489, 0.3989, 0.1625, 0.1365], grad_fn=<SigmoidBackward>)

In [198]:
input

tensor([-0.1000,  0.1000,  0.2000,  0.8000,  0.9000])

In [1]:
import torch
import torchvision

In [2]:
model = torchvision.models.vgg16(pretrained=True)
features = list(model.features)

Downloading: "https://download.pytorch.org/models/vgg16-397923af.pth" to /home/beomgon/.cache/torch/hub/checkpoints/vgg16-397923af.pth


  0%|          | 0.00/528M [00:00<?, ?B/s]

In [4]:
model.features

Sequential(
  (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (1): ReLU(inplace=True)
  (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (3): ReLU(inplace=True)
  (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (6): ReLU(inplace=True)
  (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (8): ReLU(inplace=True)
  (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (11): ReLU(inplace=True)
  (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (13): ReLU(inplace=True)
  (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (15): ReLU(inplace=True)
  (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (17): Conv2d(256, 512, kernel_si

In [6]:
# only collect layers with output feature map size (W, H) < 50
dummy_img = torch.zeros((1, 3, 800, 800)).float() # test image array

req_features = []
output = dummy_img.clone()

for feature in features:
    output = feature(output)
#     print(output.size()) => torch.Size([batch_size, channel, width, height])
    if output.size()[2] < 800//16: # 800/16=50
        break
    req_features.append(feature)
    out_channels = output.size()[1]

faster_rcnn_feature_extractor = nn.Sequential(*req_features)

output_map = faster_rcnn_feature_extractor(imgTensor)

NameError: name 'nn' is not defined

In [24]:
import torch
src = torch.arange(1, 11).reshape((2, 5))
src = torch.tensor([[2,4,1,2,9],
                   [12,14,11,12,19]])
src

tensor([[ 2,  4,  1,  2,  9],
        [12, 14, 11, 12, 19]])

In [25]:
index = torch.tensor([[0, 1, 2, 3, 0]])
index

tensor([[0, 1, 2, 3, 0]])

In [28]:
torch.zeros(4, 5, dtype=src.dtype).scatter_(0, index, src)

tensor([[2, 0, 0, 0, 9],
        [0, 4, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 2, 0]])